export const LOCAL_WHISPER_MODELS = [
  {
    name: "tiny",
    englishOnly: true,
    requiredRAM: 6,
  },

  {
    name: "base",
    englishOnly: true,
    requiredRAM: 6,
  },

  {
    name: "small",
    englishOnly: true,
    requiredRAM: 12,
  },

  {
    name: "medium",
    englishOnly: true,
    requiredRAM: 30,
  },

  {
    name: "large",
    englishOnly: false,
    version: "v3",
    requiredRAM: 60,
  },

  {
    name: "large-turbo",
    englishOnly: false,
    version: "v3",
    requiredRAM: 36,
  },
] as const;

export const WHISPER_LANGUAGES: { key: string; value: string }[] = [
  { key: "en", value: "English" },
  { key: "ar", value: "Arabic" },
  { key: "hy", value: "Armenian" },
  { key: "az", value: "Azerbaijani" },
  { key: "eu", value: "Basque" },
  { key: "be", value: "Belarusian" },
  { key: "bn", value: "Bengali" },
  { key: "bg", value: "Bulgarian" },
  { key: "ca", value: "Catalan" },
  { key: "zh", value: "Chinese" },
  { key: "hr", value: "Croatian" },
  { key: "cs", value: "Czech" },
  { key: "da", value: "Danish" },
  { key: "nl", value: "Dutch" },
  { key: "et", value: "Estonian" },
  { key: "tl", value: "Filipino" },
  { key: "fi", value: "Finnish" },
  { key: "fr", value: "French" },
  { key: "gl", value: "Galician" },
  { key: "ka", value: "Georgian" },
  { key: "de", value: "German" },
  { key: "el", value: "Greek" },
  { key: "gu", value: "Gujarati" },
  { key: "iw", value: "Hebrew" },
  { key: "hi", value: "Hindi" },
  { key: "hu", value: "Hungarian" },
  { key: "is", value: "Icelandic" },
  { key: "id", value: "Indonesian" },
  { key: "ga", value: "Irish" },
  { key: "it", value: "Italian" },
  { key: "ja", value: "Japanese" },
  { key: "kn", value: "Kannada" },
  { key: "ko", value: "Korean" },
  { key: "la", value: "Latin" },
  { key: "lv", value: "Latvian" },
  { key: "lt", value: "Lithuanian" },
  { key: "mk", value: "Macedonian" },
  { key: "ms", value: "Malay" },
  { key: "mt", value: "Maltese" },
  { key: "no", value: "Norwegian" },
  { key: "fa", value: "Persian" },
  { key: "pl", value: "Polish" },
  { key: "pt", value: "Portuguese" },
  { key: "ro", value: "Romanian" },
  { key: "ru", value: "Russian" },
  { key: "sr", value: "Serbian" },
  { key: "sk", value: "Slovak" },
  { key: "sl", value: "Slovenian" },
  { key: "es", value: "Spanish" },
  { key: "sw", value: "Swahili" },
  { key: "sv", value: "Swedish" },
  { key: "ta", value: "Tamil" },
  { key: "te", value: "Telugu" },
  { key: "th", value: "Thai" },
  { key: "tr", value: "Turkish" },
  { key: "uk", value: "Ukrainian" },
  { key: "ur", value: "Urdu" },
  { key: "vi", value: "Vietnamese" },
  { key: "cy", value: "Welsh" },
  { key: "yi", value: "Yiddish" },
];
