#ifndef MYSCRIPT_STT_H
#define MYSCRIPT_STT_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define myscript_stt_SAMPLE_RATE 16000

typedef void *myscript_stt_SttHandle;

/**
 * One transcribed utterance, in the order spoken. The string is only valid for
 * the duration of the call.
 */
typedef void (*myscript_stt_TextCallback)(const char*);

/**
 * One captured utterance as 16-bit signed PCM, mono, at `SAMPLE_RATE`, for a
 * host that transcribes elsewhere. The buffer is only valid for the call.
 */
typedef void (*myscript_stt_AudioCallback)(const int16_t*, uintptr_t);

/**
 * Microphone level while listening, so the host can draw a meter.
 */
typedef void (*myscript_stt_LevelCallback)(float);

/**
 * The take ended; true when it ended by itself after a long silence.
 */
typedef void (*myscript_stt_StoppedCallback)(bool);

/**
 * A transcription failed; listening continues.
 */
typedef void (*myscript_stt_ErrorCallback)(const char*);

/**
 * Every callback runs on a library thread, never on the caller's.
 */
typedef struct myscript_stt_Callbacks {
    myscript_stt_TextCallback text;
    myscript_stt_AudioCallback audio;
    myscript_stt_LevelCallback level;
    myscript_stt_StoppedCallback stopped;
    myscript_stt_ErrorCallback error;
} myscript_stt_Callbacks;

/**
 * Returns the last error as a C string (free with `myscript_stt_free_string`), or NULL if none.
 */
const char *myscript_stt_get_last_error(void);

/**
 * Frees a string returned by any function in this crate.
 */
void myscript_stt_free_string(char *s);

/**
 * Every callback is invoked from a library thread.
 */
myscript_stt_SttHandle myscript_stt_new(struct myscript_stt_Callbacks callbacks);

void myscript_stt_free(myscript_stt_SttHandle handle);

/**
 * Loads the model and returns once it is resident, or with the reason it is not.
 */
int myscript_stt_load(myscript_stt_SttHandle handle, const char *path);

/**
 * Frees the model once any utterance still transcribing is out.
 */
int myscript_stt_unload(myscript_stt_SttHandle handle);

/**
 * Opens the microphone and starts listening. Utterances go to the text
 * callback through the loaded model, or to the audio callback in capture-only mode.
 */
int myscript_stt_start(myscript_stt_SttHandle handle);

/**
 * Stops listening and returns once the last utterance has been delivered.
 * Blocks for as long as that transcription takes, so call it off the UI thread.
 */
int myscript_stt_stop(myscript_stt_SttHandle handle);

/**
 * Stops listening and drops whatever has not been delivered yet.
 */
int myscript_stt_cancel(myscript_stt_SttHandle handle);

bool myscript_stt_is_recording(myscript_stt_SttHandle handle);

/**
 * Selects the capture device by name. Null or empty means the system default.
 * Takes effect on the next take.
 */
int myscript_stt_set_device(myscript_stt_SttHandle handle, const char *name);

/**
 * Sets the spoken language as an ISO code; null or empty asks the model to
 * detect, which only some can. Takes effect on the next take.
 */
int myscript_stt_set_language(myscript_stt_SttHandle handle, const char *code);

/**
 * While on, takes never touch the engine: each utterance reaches the audio
 * callback as PCM for the host to transcribe elsewhere. Takes effect on the next take.
 */
int myscript_stt_set_capture_only(myscript_stt_SttHandle handle, bool enabled);

/**
 * Input device names, newline separated, the default marked with a leading '*'.
 */
char *myscript_stt_devices(void);

#endif  /* MYSCRIPT_STT_H */
