// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AffectedTablesPlaceholder() {
  return window['go']['main']['App']['AffectedTablesPlaceholder']();
}

export function CancelAICompletion(arg1) {
  return window['go']['main']['App']['CancelAICompletion'](arg1);
}

export function CancelRecording() {
  return window['go']['main']['App']['CancelRecording']();
}

export function CancelSpeechModelDownload(arg1) {
  return window['go']['main']['App']['CancelSpeechModelDownload'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeleteAIProvider(arg1) {
  return window['go']['main']['App']['DeleteAIProvider'](arg1);
}

export function DeleteCache(arg1) {
  return window['go']['main']['App']['DeleteCache'](arg1);
}

export function DeleteGoogleAuthToken() {
  return window['go']['main']['App']['DeleteGoogleAuthToken']();
}

export function DeleteLocalPage(arg1) {
  return window['go']['main']['App']['DeleteLocalPage'](arg1);
}

export function DeleteSpeechModel(arg1) {
  return window['go']['main']['App']['DeleteSpeechModel'](arg1);
}

export function DownloadSpeechModel(arg1) {
  return window['go']['main']['App']['DownloadSpeechModel'](arg1);
}

export function GetAIProviderAPIKey(arg1) {
  return window['go']['main']['App']['GetAIProviderAPIKey'](arg1);
}

export function GetAIProviders() {
  return window['go']['main']['App']['GetAIProviders']();
}

export function GetActiveAIProvider() {
  return window['go']['main']['App']['GetActiveAIProvider']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCache(arg1) {
  return window['go']['main']['App']['GetCache'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGoogleAuthToken() {
  return window['go']['main']['App']['GetGoogleAuthToken']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetLocalPage(arg1) {
  return window['go']['main']['App']['GetLocalPage'](arg1);
}

export function GetLocalPages() {
  return window['go']['main']['App']['GetLocalPages']();
}

export function GetMachine() {
  return window['go']['main']['App']['GetMachine']();
}

export function GetMicInputDevices() {
  return window['go']['main']['App']['GetMicInputDevices']();
}

export function GetNotionPageBlocks(arg1) {
  return window['go']['main']['App']['GetNotionPageBlocks'](arg1);
}

export function GetNotionPages() {
  return window['go']['main']['App']['GetNotionPages']();
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function GetSpeechModels() {
  return window['go']['main']['App']['GetSpeechModels']();
}

export function HasConfiguredAIProvider() {
  return window['go']['main']['App']['HasConfiguredAIProvider']();
}

export function HasLegacyWhisperFiles() {
  return window['go']['main']['App']['HasLegacyWhisperFiles']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function IsGoogleAuthEnabled() {
  return window['go']['main']['App']['IsGoogleAuthEnabled']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function IsWitAIAvailable() {
  return window['go']['main']['App']['IsWitAIAvailable']();
}

export function ListAIModels(arg1, arg2) {
  return window['go']['main']['App']['ListAIModels'](arg1, arg2);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function RefreshGoogleAuthToken() {
  return window['go']['main']['App']['RefreshGoogleAuthToken']();
}

export function RemoveLegacyWhisperFiles() {
  return window['go']['main']['App']['RemoveLegacyWhisperFiles']();
}

export function SaveAIProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveAIProvider'](arg1, arg2);
}

export function SaveCache(arg1, arg2) {
  return window['go']['main']['App']['SaveCache'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveLocalPage(arg1) {
  return window['go']['main']['App']['SaveLocalPage'](arg1);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2);
}

export function SetActiveAIProvider(arg1) {
  return window['go']['main']['App']['SetActiveAIProvider'](arg1);
}

export function StartAICompletion(arg1) {
  return window['go']['main']['App']['StartAICompletion'](arg1);
}

export function StartGoogleAuthorization() {
  return window['go']['main']['App']['StartGoogleAuthorization']();
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StartSynchronizer() {
  return window['go']['main']['App']['StartSynchronizer']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function StopSynchronizer() {
  return window['go']['main']['App']['StopSynchronizer']();
}

export function TestAIProvider(arg1, arg2) {
  return window['go']['main']['App']['TestAIProvider'](arg1, arg2);
}

export function UpdateLocalPageOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLocalPageOrder'](arg1, arg2, arg3);
}
