// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function GetConfig():Promise<repository.Config>;

export function SaveConfig(arg1:repository.Config):Promise<void>;
