// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNotionPageBlocks(arg1) {
  return window['go']['main']['App']['GetNotionPageBlocks'](arg1);
}

export function GetNotionPages() {
  return window['go']['main']['App']['GetNotionPages']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
