name: Build Wails App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          # Windows ARM64 needs special handling
          - os: windows-latest
            arch: arm64
          # Linux ARM64 builds might need specific runners
          - os: ubuntu-latest
            arch: arm64

    runs-on: ${{ matrix.os }}
    env:
      CGO_CFLAGS_ALLOW: "-mfma|-mf16c"

    steps:
      - uses: actions/checkout@v4

      - name: Create API Keys file
        run: |
          mkdir -p internal/transcribe/wait.ai
          "${{ secrets.WAIT_API_KEYS }}" > internal/transcribe/wait.ai/keys.go

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw
          choco install cmake
          choco install nsis

      - name: Install Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          wails build -platform windows/${{ matrix.arch }} -nsis -upx -obfuscated

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          wails build -platform linux/${{ matrix.arch }} -upx -obfuscated

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: |
          wails build -platform darwin/${{ matrix.arch }} -upx -obfuscated

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}-build
          path: |
            build/bin/*
